# Generated by Django 5.1.15 on 2026-04-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_crewrequirement_talentrequirement'),
        ('talent', '0007_talentpayment_project_talenttimelog_booking_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='talentpayment',
            unique_together={('talent', 'project', 'period_month', 'period_year')},
        ),
        migrations.AddField(
            model_name='talentpayment',
            name='stripe_payout_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talentpayment',
            name='stripe_transfer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
