# Generated by Django 5.1.15 on 2026-03-01 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_type', models.CharField(choices=[('model', 'Model'), ('actor', 'Actor'), ('voiceover', 'Voiceover'), ('dancer', 'Dancer'), ('other', 'Other')], default='model', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('height', models.CharField(blank=True, max_length=20)),
                ('measurements', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'talent'}, on_delete=django.db.models.deletion.CASCADE, related_name='talent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='projects.shoot')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='talent.talentprofile')),
            ],
            options={
                'unique_together': {('shoot', 'talent')},
            },
        ),
    ]
