# Generated by Django 5.1.15 on 2026-03-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_raw_material_url'),
        ('talent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attire_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='approval_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='performance_capability',
            field=models.CharField(choices=[('model_only', 'Model Only (No Dialogue)'), ('with_dialogue', 'Can Perform with Dialogue'), ('both', 'Both Model & Dialogue')], default='model_only', max_length=20),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='profile_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='specializations',
            field=models.TextField(blank=True, help_text="Special skills, e.g. 'Can ride a bike, swim, martial arts'"),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='talent_type',
            field=models.CharField(choices=[('model', 'Model'), ('actor', 'Actor'), ('voiceover', 'Voiceover'), ('dancer', 'Dancer'), ('livestream', 'Livestream Host'), ('other', 'Other')], default='model', max_length=20),
        ),
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('acting', 'Acting Performance'), ('livestream', 'Livestream Campaign'), ('commercial', 'Commercial'), ('print', 'Print Campaign'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TalentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='talent_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TalentTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_time_logs', to='projects.project')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.shoot')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TalentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('talent', 'period_month', 'period_year')},
            },
        ),
    ]
