# Generated by Django 5.1.15 on 2026-03-07 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0002_booking_attire_requirements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('period', models.CharField(choices=[('am', 'AM (Morning)'), ('pm', 'PM (Afternoon)'), ('full', 'Full Day')], default='full', max_length=4)),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('tentative', 'Tentative')], default='available', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['date', 'period'],
                'unique_together': {('talent', 'date', 'period')},
            },
        ),
    ]
