# Generated by Django 5.1.15 on 2026-03-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0003_talentavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentprofile',
            name='race_ethnicity',
            field=models.CharField(blank=True, choices=[('asian', 'Asian'), ('black_african', 'Black / African'), ('east_asian', 'East Asian'), ('hispanic_latino', 'Hispanic / Latino'), ('middle_eastern', 'Middle Eastern'), ('mixed', 'Mixed / Multiracial'), ('native_american', 'Native American / Indigenous'), ('pacific_islander', 'Pacific Islander'), ('south_asian', 'South Asian'), ('southeast_asian', 'Southeast Asian'), ('white_caucasian', 'White / Caucasian'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='skin_tone',
            field=models.CharField(blank=True, choices=[('very_fair', 'Very Fair'), ('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('tan', 'Tan'), ('brown', 'Brown'), ('dark', 'Dark'), ('deep', 'Deep')], max_length=50),
        ),
    ]
