# Generated by Django 5.1.15 on 2026-03-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0004_add_race_ethnicity_and_skin_tone_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentprofile',
            name='race_ethnicity',
        ),
        migrations.AddField(
            model_name='talentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20),
        ),
        migrations.AlterField(
            model_name='talentprofile',
            name='skin_tone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
