# Generated by Django 5.1.15 on 2026-03-30 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_crewrequirement_talentrequirement'),
        ('talent', '0006_restore_race_ethnicity'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentpayment',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_payments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='talenttimelog',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='talent.booking'),
        ),
        migrations.AddField(
            model_name='talenttimelog',
            name='log_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
