# Generated by Django 5.1.15 on 2026-04-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talent', '0008_alter_talentpayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='talentpayment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='talentpayment',
            name='source_time_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='talent.talenttimelog'),
        ),
    ]
