# Generated by Django 5.1.15 on 2026-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='raw_material_url',
            field=models.URLField(blank=True, help_text='Google Drive link for raw materials', max_length=500),
        ),
    ]
