# Generated by Django 5.1.15 on 2026-03-01 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_raw_material_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('shoot_date', models.DateField()),
                ('call_time', models.TimeField()),
                ('est_wrap_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('parking_info', models.TextField(blank=True)),
                ('weather_notes', models.CharField(blank=True, max_length=255)),
                ('wardrobe_instructions', models.TextField(blank=True)),
                ('hair_makeup_notes', models.TextField(blank=True)),
                ('production_notes', models.TextField(blank=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_sheets', to='projects.project')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_sheets', to='projects.shoot')),
            ],
            options={
                'ordering': ['-shoot_date'],
            },
        ),
        migrations.CreateModel(
            name='CallSheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('talent', 'Talent'), ('crew', 'Crew')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('call_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='projects.callsheet')),
            ],
            options={
                'ordering': ['person_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('pre_production', 'Pre-Production'), ('production', 'Production Day'), ('post_production', 'Post-Production'), ('equipment', 'Equipment'), ('general', 'General')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='projects.checklist')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('note', 'Note'), ('issue', 'Issue'), ('decision', 'Decision'), ('change', 'Change Order'), ('milestone', 'Milestone')], default='note', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='projects.project')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to='projects.shoot')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
    ]
