# Generated by Django 5.1.15 on 2026-03-07 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_consideration_models'),
        ('projects', '0004_shoot_description'),
        ('talent', '0003_talentavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_considerations', to='crew.crewprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_considerations', to='projects.project')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('project', 'crew')},
            },
        ),
        migrations.CreateModel(
            name='TalentConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_considerations', to='projects.project')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_considerations', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('project', 'talent')},
            },
        ),
    ]
