# Generated by Django 5.1.15 on 2026-03-29 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_production_requirement_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrewRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_role', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_requirements_list', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TalentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talent_type', models.CharField(choices=[('model', 'Model'), ('actor', 'Actor'), ('voiceover', 'Voiceover'), ('dancer', 'Dancer'), ('livestream', 'Livestream Host'), ('other', 'Other')], max_length=20)),
                ('count', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_requirements', to='projects.project')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
