# Generated by Django 5.1.15 on 2026-04-28 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_crewrequirement_talentrequirement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_production_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_production_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_crew_availability_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_status',
            field=models.CharField(choices=[('unsent', 'Unsent'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='unsent', max_length=20),
        ),
        migrations.AddField(
            model_name='crewconsideration',
            name='inquiry_token_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_production_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_production_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_talent_availability_inquiries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_status',
            field=models.CharField(choices=[('unsent', 'Unsent'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='unsent', max_length=20),
        ),
        migrations.AddField(
            model_name='talentconsideration',
            name='inquiry_token_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
