# Generated by Django 5.1.15 on 2026-03-07 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0001_initial'),
        ('talent', '0003_talentavailability'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='talent_suggestions', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talent_suggestions_sent', to=settings.AUTH_USER_MODEL)),
                ('talents', models.ManyToManyField(related_name='suggestions', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
