# Generated by Django 5.1.15 on 2026-04-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientportal', '0003_talentrostershare_delete_talentsuggestion'),
        ('projects', '0008_crewconsideration_inquiry_pay_rate_and_more'),
        ('talent', '0008_alter_talentpayment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talentrostershare',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='talent_shortlists/'),
        ),
        migrations.AddField(
            model_name='talentrostershare',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talent_roster_shares', to='projects.project'),
        ),
        migrations.CreateModel(
            name='TalentRosterShareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('client_favorite', models.BooleanField(default=False)),
                ('client_note', models.TextField(blank=True)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clientportal.talentrostershare')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_roster_items', to='talent.talentprofile')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('share', 'talent')},
            },
        ),
    ]
