# Generated by Django 5.1.15 on 2026-03-01 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_type', models.CharField(choices=[('camera', 'Camera'), ('lens', 'Lens'), ('lighting', 'Lighting'), ('audio', 'Audio'), ('grip', 'Grip'), ('other', 'Other')], default='camera', max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('checked_out', 'Checked Out'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_role', models.CharField(choices=[('photographer', 'Photographer'), ('videographer', 'Videographer'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('assistant', 'Assistant'), ('other', 'Other')], default='photographer', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('availability', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'crew'}, on_delete=django.db.models.deletion.CASCADE, related_name='crew_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checkouts', to='crew.crewprofile')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='crew.equipment')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment_checkouts', to='projects.shoot')),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_on_shoot', models.CharField(blank=True, choices=[('photographer', 'Photographer'), ('videographer', 'Videographer'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('assistant', 'Assistant'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='projects.shoot')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='crew.crewprofile')),
            ],
            options={
                'unique_together': {('shoot', 'crew')},
            },
        ),
    ]
