# Generated by Django 5.1.15 on 2026-03-01 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0001_initial'),
        ('projects', '0002_project_raw_material_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crewassignment',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='day_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='equipment_owned',
            field=models.TextField(blank=True, help_text='Personal equipment the crew member can bring'),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='crew_photos/'),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='skills',
            field=models.TextField(blank=True, help_text='Technical skills and specializations'),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crewassignment',
            name='role_on_shoot',
            field=models.CharField(blank=True, choices=[('photographer', 'Photographer'), ('dop', 'Director of Photography'), ('videographer', 'Videographer'), ('gaffer', 'Gaffer'), ('grip', 'Grip'), ('wardrobe', 'Wardrobe'), ('set_design', 'Set Design'), ('bts', 'Behind-the-Scene'), ('pa', 'Production Assistant'), ('ac', 'Assistant Camera'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='crewprofile',
            name='crew_role',
            field=models.CharField(choices=[('photographer', 'Photographer'), ('dop', 'Director of Photography'), ('videographer', 'Videographer'), ('gaffer', 'Gaffer'), ('grip', 'Grip'), ('wardrobe', 'Wardrobe'), ('set_design', 'Set Design'), ('bts', 'Behind-the-Scene'), ('pa', 'Production Assistant'), ('ac', 'Assistant Camera'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('other', 'Other')], default='photographer', max_length=30),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('talent', 'Talent'), ('crew', 'Crew')], max_length=10)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('professionalism', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('skill_level', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('reliability', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_given', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='projects.project')),
                ('subject_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrewAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('tentative', 'Tentative')], default='available', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to='crew.crewprofile')),
            ],
            options={
                'verbose_name_plural': 'Crew availabilities',
                'ordering': ['date'],
                'unique_together': {('crew', 'date')},
            },
        ),
    ]
