# Generated by Django 5.1.15 on 2026-03-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0004_consideration_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewassignment',
            name='role_on_shoot',
            field=models.CharField(blank=True, choices=[('director', 'Director'), ('photographer', 'Photographer'), ('dop', 'Director of Photography'), ('videographer', 'Videographer'), ('first_ac', '1st Assistant Camera'), ('second_ac', '2nd Assistant Camera'), ('gaffer', 'Gaffer'), ('grip', 'Grip'), ('electric', 'Electric'), ('wardrobe', 'Wardrobe'), ('set_design', 'Set Design'), ('bts', 'Behind-the-Scene'), ('pa', 'Production Assistant'), ('ac', 'Assistant Camera'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('crafty', 'Crafty'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='crewprofile',
            name='crew_role',
            field=models.CharField(choices=[('director', 'Director'), ('photographer', 'Photographer'), ('dop', 'Director of Photography'), ('videographer', 'Videographer'), ('first_ac', '1st Assistant Camera'), ('second_ac', '2nd Assistant Camera'), ('gaffer', 'Gaffer'), ('grip', 'Grip'), ('electric', 'Electric'), ('wardrobe', 'Wardrobe'), ('set_design', 'Set Design'), ('bts', 'Behind-the-Scene'), ('pa', 'Production Assistant'), ('ac', 'Assistant Camera'), ('audio', 'Audio'), ('lighting', 'Lighting'), ('hair_makeup', 'Hair & Makeup'), ('stylist', 'Stylist'), ('crafty', 'Crafty'), ('other', 'Other')], default='photographer', max_length=30),
        ),
    ]
