# Generated by Django 5.1.15 on 2026-04-30 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0006_crewprofile_stripe_account_id_and_more'),
        ('projects', '0008_crewconsideration_inquiry_pay_rate_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='crewpayment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CrewTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_applied', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('log_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('notified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_logs', to='crew.crewassignment')),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='crew.crewprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_time_logs', to='projects.project')),
                ('shoot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.shoot')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='crewpayment',
            name='source_time_log',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='crew.crewtimelog'),
        ),
    ]
