# Generated by Django 5.1.15 on 2026-03-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('projects', '0005_consideration_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='expense_receipts/'),
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('talent', 'Talent'), ('crew', 'Crew'), ('equipment', 'Equipment'), ('location', 'Location'), ('catering', 'Catering'), ('travel', 'Travel'), ('post_production', 'Post Production'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_allocations', to='projects.project')),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('project', 'category')},
            },
        ),
    ]
