# Generated by Django 5.1.15 on 2026-03-09 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_add_receipt_and_budget_allocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='reimbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reimbursement_proof',
            field=models.FileField(blank=True, null=True, upload_to='reimbursement_proofs/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='budgetallocation',
            name='category',
            field=models.CharField(choices=[('talent', 'Talent'), ('crew', 'Crew'), ('props', 'Props'), ('equipment', 'Equipment'), ('equipment_rental', 'Equipment Rental'), ('location', 'Location'), ('catering', 'Catering'), ('travel', 'Travel'), ('gas', 'Gas'), ('post_production', 'Post Production'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('talent', 'Talent'), ('crew', 'Crew'), ('props', 'Props'), ('equipment', 'Equipment'), ('equipment_rental', 'Equipment Rental'), ('location', 'Location'), ('catering', 'Catering'), ('travel', 'Travel'), ('gas', 'Gas'), ('post_production', 'Post Production'), ('miscellaneous', 'Miscellaneous'), ('other', 'Other')], max_length=20),
        ),
    ]
