# Generated by Django 5.1.15 on 2026-03-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='file_url',
            new_name='file',
        ),
        migrations.AddField(
            model_name='deliverable',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='deliverables/thumbs/'),
        ),
    ]
