# Generated by Django 5.1.15 on 2026-03-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0002_rename_file_url_deliverable_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('talent', 'Talent Agreement'), ('crew', 'Crew Agreement'), ('client', 'Client Agreement'), ('location_agreement', 'Location Agreement'), ('budget_template', 'Budget Template'), ('production_schedule', 'Production Schedule'), ('nda', 'NDA'), ('other', 'Other')], max_length=25),
        ),
    ]
