# Generated by Django 5.1.15 on 2026-03-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0003_crewavailability_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crewavailability',
            options={'ordering': ['date', 'period'], 'verbose_name_plural': 'Crew availabilities'},
        ),
    ]
