# Generated by Django 5.1.15 on 2026-04-05 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crew', '0005_alter_crewassignment_role_on_shoot_and_more'),
        ('projects', '0007_crewrequirement_talentrequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='crewprofile',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='crewprofile',
            name='stripe_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CrewPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_month', models.PositiveIntegerField()),
                ('period_year', models.PositiveIntegerField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('stripe_transfer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_payout_status', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crew.crewprofile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_payments', to='projects.project')),
            ],
            options={
                'ordering': ['-period_year', '-period_month'],
                'unique_together': {('crew', 'project', 'period_month', 'period_year')},
            },
        ),
    ]
