# Generated by Django 5.1.15 on 2026-04-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliverables', '0005_contract_draft_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='contract_signatures/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
